export default {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_LOADING_MESSAGE: 'SET_LOADING_MESSAGE',
  SET_IS_MODAL_OPEN: 'SET_IS_MODAL_OPEN',
  SET_MODAL_COMPONENT_NAME: 'SET_MODAL_COMPONENT_NAME',
  SET_MODAL_COMPONENT_PROPS: 'SET_MODAL_COMPONENT_PROPS',
};
